import asyncio
import os
from pathlib import Path
from google import genai


# ── train_from_samples ────────────────────────────────────────────────
# Called by flask_server.py /train endpoint.
# Saves samples locally and writes custom_voice_config.py.
# Real Gemini voice cloning is not yet available via the public API;
# samples are stored so they are ready when the API supports it.
def train_from_samples(sample_paths: list) -> str | None:
    """Save samples and write custom_voice_config.py.

    Returns a local voice_id string on success, or None if no paths given.
    """
    if not sample_paths:
        return None

    # Generate a local voice ID based on timestamp
    voice_id = f"local_voice_{int(asyncio.get_event_loop().time()) if asyncio.get_event_loop().is_running() else int(__import__('time').time())}"

    # Write custom_voice_config.py so /tts can pick up the voice
    _write_voice_config(voice_id)

    print(f"Voice samples saved ({len(sample_paths)} clips). Voice ID: {voice_id}")
    print("Note: Full voice cloning requires an external API (ElevenLabs, etc.).")
    print("Set ELEVENLABS_API_KEY and update voice_training.py to enable real cloning.")

    return voice_id


def _write_voice_config(voice_id: str):
    """Write custom_voice_config.py with the trained voice ID."""
    config_code = f'''# Auto-generated by voice_training.py
CUSTOM_VOICE_ID = "{voice_id}"

def get_custom_voice_settings(context):
    base = {{
        "voice_id": CUSTOM_VOICE_ID,
        "speaking_rate": 1.0,
        "pitch": 0,
        "emotion": "professional"
    }}
    if context == "SCAM_DETECTED":
        base.update({{"emotion": "firm", "speaking_rate": 0.9}})
    elif context == "VERIFICATION":
        base.update({{"emotion": "calm", "speaking_rate": 1.0}})
    elif context == "cloned":
        pass  # use base defaults for cloned voice
    else:
        base.update({{"emotion": "helpful", "speaking_rate": 1.1}})
    return base
'''
    with open("custom_voice_config.py", "w") as f:
        f.write(config_code)
    print(f"custom_voice_config.py written with voice_id={voice_id}")


# ── VoiceTrainer (interactive CLI tool) ───────────────────────────────
class VoiceTrainer:
    def __init__(self):
        self.client = genai.Client()

    async def create_voice_profile(self, voice_samples_path):
        """Print recording guide for training phrases."""
        training_phrases = [
            "Hello, this is a legal screening service.",
            "I need to verify some information.",
            "Your call appears to be fraudulent.",
            "Thank you for calling our office.",
            "May I know who is calling and the purpose of your call?",
            "This number is being reported to the authorities.",
            "What type of legal assistance do you need?",
            "I'll need to verify this before proceeding.",
            "Do not call again.",
            "Let me connect you to our intake system.",
        ]
        print("Voice Training Setup")
        print("Please record these phrases in your natural voice:")
        print("-" * 50)
        for i, phrase in enumerate(training_phrases, 1):
            print(f'{i}. "{phrase}"')
            print(f"   Save as: voice_sample_{i:02d}.wav")
            print()
        print("Recording Instructions:")
        print("- Use a quiet environment")
        print("- Speak naturally, don't over-enunciate")
        print("- Record in .wav format, 44.1kHz")
        print("- Each phrase: 3-5 seconds long")
        print("- Save all files in:", voice_samples_path)

    async def train_custom_voice(self, voice_samples_path, voice_name="my_legal_voice"):
        """Train custom voice model via Gemini API (when available)."""
        try:
            voice_files = [
                f"{voice_samples_path}/voice_sample_{i:02d}.wav"
                for i in range(1, 11)
            ]
            voice_profile = await self.client.voices.create(
                name=voice_name,
                samples=voice_files,
                description="Legal paralegal voice",
                language="en-US",
            )
            print(f"Voice profile created: {voice_profile.id}")
            print("Training may take 10-30 minutes...")
            while voice_profile.status != "ready":
                await asyncio.sleep(30)
                voice_profile = await self.client.voices.get(voice_profile.id)
                print(f"Training status: {voice_profile.status}")
            print(f"Voice training complete! Voice ID: {voice_profile.id}")
            return voice_profile.id
        except Exception as e:
            print(f"Training failed: {e}")
            return None

    def update_scam_screener_with_custom_voice(self, voice_id):
        _write_voice_config(voice_id)
        print("Custom voice config created!")


async def main():
    trainer = VoiceTrainer()
    print("Custom Voice Training for Scam Screener")
    print("=" * 50)
    await trainer.create_voice_profile("./voice_samples")
    input("\nPress Enter after recording all voice samples...")
    voice_id = await trainer.train_custom_voice("./voice_samples")
    if voice_id:
        trainer.update_scam_screener_with_custom_voice(voice_id)
        print(f"Your scam screener will now speak with YOUR voice!")
        print(f"Voice ID: {voice_id}")


if __name__ == "__main__":
    asyncio.run(main())
